const data = [
  { countryNo: 1, code: 'ST01', stateName: 'Maharashtra', statusNo: 1, statusRemarks: null },
  { countryNo: 2, code: 'ST02', stateName: 'Gujarat', statusNo: 2, statusRemarks: 'State activated successfully.' },
  {
    countryNo: 3,
    code: 'ST03',
    stateName: 'Karnataka',
    statusNo: 2,
    statusRemarks: 'Marked inactive for verification.',
  },
  { countryNo: 1, code: 'ST01U', stateName: 'Maharashtra Updated', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: '', stateName: 'Rajasthan', statusNo: 1, statusRemarks: null },
  { countryNo: 2, code: ' ST09 ', stateName: 'Goa', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'CODE06', stateName: 'Punjab', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'CODE007', stateName: 'Haryana', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'CD005', stateName: 'Kerala', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'A', stateName: 'Bihar', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'ST01', stateName: 'DuplicateCodeState', statusNo: 1, statusRemarks: null },
  { countryNo: 2, code: 'ST15', stateName: '', statusNo: 1, statusRemarks: null },
  { countryNo: 1, code: 'ST16', stateName: ' Himachal Pradesh ', statusNo: 1, statusRemarks: null },
  {
    countryNo: 1,
    code: 'ST17',
    stateName: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    statusNo: 1,
    statusRemarks: null,
  },
  {
    countryNo: 1,
    code: 'ST18',
    stateName: 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    statusNo: 1,
    statusRemarks: null,
  },
  {
    countryNo: 2,
    code: 'ST19',
    stateName: 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    statusNo: 1,
    statusRemarks: null,
  },
  { countryNo: 2, code: 'ST20', stateName: 'Z', statusNo: 1, statusRemarks: null },
  { countryNo: 3, code: 'ST21', stateName: 'Maharashtra', statusNo: 1, statusRemarks: null },
  { countryNo: 2, code: 'ST22', stateName: 'Tripura', statusNo: null, statusRemarks: null },
  { countryNo: 1, code: 'ST23', stateName: 'Nagaland', statusNo: 2, statusRemarks: ' Status remark with spaces. ' },
  {
    countryNo: 1,
    code: 'ST49',
    stateName: 'Assam',
    statusNo: 2,
    statusRemarks:
      'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR',
  },
  {
    countryNo: 2,
    code: 'ST50',
    stateName: 'Manipur',
    statusNo: 2,
    statusRemarks:
      'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
  },
  {
    countryNo: 3,
    code: 'ST51',
    stateName: 'Meghalaya',
    statusNo: 2,
    statusRemarks:
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  },
  { countryNo: 1, code: 'ST27', stateName: 'Odisha', statusNo: 2, statusRemarks: 'O' },
];

// Map of country numbers to names
const countryMap = {
  1: 'India',
  2: 'United States',
  3: 'Germany',
};

// Transform
const updated = data.map((item, index) => ({
  [`SM_0${index + 5}`]: {
    query: 'ind',
    countryName: countryMap[item.countryNo] || 'Unknown',
    code: item.code ? item.code.trim() : '',
    name: item.stateName ? item.stateName.trim() : '',
    status: item.statusNo ? String(item.statusNo) : '',
    statusRemarks: item.statusRemarks ? item.statusRemarks.trim() : '',
  },
}));

console.log(JSON.stringify(updated, null, 2));
[
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST01',
    name: 'Maharashtra',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST02',
    name: 'Gujarat',
    status: '2',
    statusRemarks: 'State activated successfully.',
  },
  {
    query: 'ind',
    countryName: 'Germany',
    code: 'ST03',
    name: 'Karnataka',
    status: '2',
    statusRemarks: 'Marked inactive for verification.',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST01U',
    name: 'Maharashtra Updated',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: '',
    name: 'Rajasthan',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST09',
    name: 'Goa',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'CODE06',
    name: 'Punjab',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'CODE007',
    name: 'Haryana',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'CD005',
    name: 'Kerala',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'A',
    name: 'Bihar',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST01',
    name: 'DuplicateCodeState',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST15',
    name: '',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST16',
    name: 'Himachal Pradesh',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST17',
    name: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST18',
    name: 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST19',
    name: 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST20',
    name: 'Z',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'Germany',
    code: 'ST21',
    name: 'Maharashtra',
    status: '1',
    statusRemarks: '',
  },
  {
    query: 'Uni',
    countryName: 'United States',
    code: 'ST22',
    name: 'Tripura',
    status: '',
    statusRemarks: '',
  },
  {
    query: 'ind',
    countryName: 'India',
    code: 'ST23',
    name: 'Nagaland',
    status: '2',
    statusRemarks: 'Status remark with spaces.',
  },
];
